import { contextBridge, ipcRenderer } from "electron";
import { autoGeneratedServices } from "../main/generated/preload-services";

const api = {};

// Use `contextBridge` APIs to expose Electron APIs to
// renderer only if context isolation is enabled, otherwise
// just add to the DOM global.
if (process.contextIsolated) {
	try {
		contextBridge.exposeInMainWorld("electronAPI", {
			...autoGeneratedServices,
		});

		// Expose IPC listener for theme changes
		contextBridge.exposeInMainWorld("electronIPC", {
			onThemeChange: (callback: (theme: string) => void) => {
				ipcRenderer.on("theme:set", (_, theme) => callback(theme));
			},
		});
	} catch (error) {
		console.error("Preload: Error exposing services", { error });
	}
} else {
	// @ts-expect-error (define in dts)
	window.api = api;
}
