import { PLATFORM } from "@electron/main/constants/index";
import { providerStorage } from "@electron/main/services/storage-service/provider-storage";
import { exec } from "child_process";
import { app, type IpcMainInvokeEvent } from "electron";
import fs from "fs";
import path from "path";
import { promisify } from "util";

const execAsync = promisify(exec);

export class DevLauncherService {
	/** Track which engine was used to launch, so we can stop with the same one */
	private activeEngine: "podman" | "docker" | null = null;

	/**
	 * Get the ai302/ runtime directory.
	 * Mirrors LocalVibeService logic independently:
	 * - Packaged macOS: ~/Documents/ai302
	 * - Packaged other: ~/ai302
	 * - Development: <cwd>/ai302
	 */
	private getComposeDir(): string {
		if (app.isPackaged) {
			return PLATFORM.IS_MAC
				? path.join(app.getPath("documents"), "ai302")
				: path.join(app.getPath("home"), "ai302");
		}
		return path.join(process.cwd(), "ai302");
	}

	/**
	 * Generate a docker-compose.dev.yml with the user-specified image.
	 * Hardcodes default ports, reads API key from provider storage.
	 */
	private async generateDevCompose(imageAddress: string): Promise<string> {
		const composeDir = this.getComposeDir();
		const devComposePath = path.join(composeDir, "docker-compose.dev.yml");

		// Read API key directly from app storage (no .env dependency)
		const { apiKey } = await providerStorage.validate302AIProvider();

		const content = `# Auto-generated by DevLauncherService — do not edit
services:
  local-cc-api:
    image: ${imageAddress}
    container_name: local-cc-api
    ports:
      - "8123:8000"
      - "18123:18789"
    user: "0"
    environment:
      - DB_SQLITE_PATH=/home/user/db/app.db
      - ROOT_SAVE_PATH=/home/user
      - ANTHROPIC_BASE_URL=https://api.302.ai
      - ANTHROPIC_AUTH_TOKEN=${apiKey}
      - ANTHROPIC_DEFAULT_HAIKU_MODEL=gpt-5.2
      - AI302_API_KEY=${apiKey}
      - IS_SANDBOX=1
    volumes:
      - type: bind
        source: ${composeDir}
        target: /home/user
    restart: unless-stopped
`;

		// Ensure directory exists
		if (!fs.existsSync(composeDir)) {
			fs.mkdirSync(composeDir, { recursive: true });
		}

		fs.writeFileSync(devComposePath, content, "utf-8");
		return devComposePath;
	}

	/**
	 * Ensure Podman machine is running before executing compose commands.
	 * - Linux: Podman runs rootless, no machine needed
	 * - macOS/Windows: start ai302-machine if not already running
	 * - Polls `podman ps` to confirm readiness
	 */
	private async ensurePodmanMachineRunning(): Promise<{ isOk: boolean; error?: string }> {
		// Linux runs rootless — no VM needed
		if (process.platform === "linux") {
			console.log("[DevLauncherService] Linux detected, skipping machine start");
			return { isOk: true };
		}

		// Check if podman is already responsive
		try {
			await execAsync("podman ps");
			console.log("[DevLauncherService] Podman already responsive");
			return { isOk: true };
		} catch {
			console.log("[DevLauncherService] Podman not responsive, starting machine...");
		}

		// Start the machine
		try {
			const { stderr } = await execAsync("podman machine start ai302-machine");
			console.log("[DevLauncherService] podman machine start output:", stderr);
		} catch (error) {
			const msg = error instanceof Error ? error.message : String(error);
			// "already running" is fine
			if (!msg.includes("already running")) {
				return { isOk: false, error: `Failed to start Podman machine: ${msg}` };
			}
			console.log("[DevLauncherService] Machine already running");
		}

		// Poll until podman is ready (up to 60s)
		const ready = await this.waitForPodmanReady(60_000);
		if (!ready) {
			return {
				isOk: false,
				error:
					"Podman machine started but not responding after 60s. Try `podman machine stop ai302-machine` then retry.",
			};
		}

		return { isOk: true };
	}

	/**
	 * Poll `podman ps` until it succeeds or timeout is reached.
	 */
	private async waitForPodmanReady(timeoutMs: number): Promise<boolean> {
		const start = Date.now();
		const interval = 2000;

		while (Date.now() - start < timeoutMs) {
			try {
				await execAsync("podman ps");
				console.log("[DevLauncherService] Podman is ready");
				return true;
			} catch {
				console.log("[DevLauncherService] Podman not ready yet, retrying...");
				await new Promise((r) => setTimeout(r, interval));
			}
		}
		return false;
	}

	/**
	 * Launch a dev sandbox container with the specified image and engine.
	 * For Podman: ensures the machine is running first.
	 */
	async launchDevSandbox(
		_event: IpcMainInvokeEvent,
		imageAddress: string,
		engine: string,
	): Promise<{ isOk: boolean; error?: string }> {
		try {
			// For Podman, ensure machine is running first
			if (engine === "podman") {
				const machineResult = await this.ensurePodmanMachineRunning();
				if (!machineResult.isOk) {
					return machineResult;
				}
			}

			const devComposePath = await this.generateDevCompose(imageAddress);

			const cmd =
				engine === "podman"
					? `podman-compose -f "${devComposePath}" up -d --force-recreate --pull always`
					: `docker compose -f "${devComposePath}" up -d --force-recreate --pull always`;

			await execAsync(cmd, { cwd: this.getComposeDir() });
			this.activeEngine = engine as "podman" | "docker";
			return { isOk: true };
		} catch (error) {
			const message = error instanceof Error ? error.message : String(error);
			console.error("[DevLauncherService] Launch failed:", message);
			return { isOk: false, error: message };
		}
	}

	/**
	 * Stop the dev sandbox container and Podman machine (if Podman was used).
	 */
	async stopDevSandbox(_event: IpcMainInvokeEvent): Promise<{ isOk: boolean; error?: string }> {
		try {
			const composeDir = this.getComposeDir();
			const devComposePath = path.join(composeDir, "docker-compose.dev.yml");

			if (!fs.existsSync(devComposePath)) {
				return { isOk: true }; // Nothing to stop
			}

			const engine = this.activeEngine ?? "docker";

			// Stop compose containers
			const composeCmd =
				engine === "podman"
					? `podman-compose -f "${devComposePath}" stop`
					: `docker compose -f "${devComposePath}" stop`;
			await execAsync(composeCmd, { cwd: composeDir });

			// Stop Podman machine (Linux runs rootless, no machine to stop)
			if (engine === "podman" && process.platform !== "linux") {
				try {
					await execAsync("podman machine stop ai302-machine");
					console.log("[DevLauncherService] Podman machine stopped");
				} catch (error) {
					const msg = error instanceof Error ? error.message : String(error);
					// "not running" is fine
					if (!msg.includes("not running")) {
						console.warn("[DevLauncherService] Failed to stop machine:", msg);
					}
				}
			}

			this.activeEngine = null;
			return { isOk: true };
		} catch (error) {
			const message = error instanceof Error ? error.message : String(error);
			console.error("[DevLauncherService] Stop failed:", message);
			return { isOk: false, error: message };
		}
	}
}

export const devLauncherService = new DevLauncherService();
