name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: macos-latest
            arch: arm64
          - os: macos-latest
            arch: x64
          - os: macos-latest
            arch: universal
          - os: ubuntu-latest
            arch: x64
          - os: windows-latest
            arch: x64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: "pnpm"

      - name: Import Code-Signing Certificates (macOS)
        if: startsWith(matrix.os, 'macos-')
        uses: Apple-Actions/import-codesign-certs@v5
        with:
          p12-file-base64: ${{ secrets.MAC_CERTS }}
          p12-password: ${{ secrets.MAC_CERTS_PASSWORD }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts
        env:
          NODE_OPTIONS: --max-old-space-size=8192

      - name: Rebuild Windows native modules
        if: matrix.os == 'windows-latest'
        run: pnpm rebuild electron-winstaller @bitdisaster/exe-icon-extractor electron-wix-msi

      - name: Generate paraglide files
        run: npx @inlang/paraglide-js compile --project ./project.inlang --outdir ./src/lib/paraglide

      - name: Run quality checks
        run: |
          npx eslint electron/main/
          pnpm run check

      - name: Create GitHub release (Ubuntu only)
        if: matrix.os == 'ubuntu-latest'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Extract version from tag
          VERSION=${GITHUB_REF#refs/tags/}
          # Create release if it doesn't exist
          if ! gh release view "$VERSION" >/dev/null 2>&1; then
            gh release create "$VERSION" --title "$VERSION" --notes "Release $VERSION" --prerelease
          fi

      - name: Build and release
        if: matrix.arch != 'universal'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_OPTIONS: --max-old-space-size=8192
          # macOS 签名和公证环境变量
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        run: pnpm run publish -- --arch=${{ matrix.arch }}

      # Universal binary build steps - 重新打包未签名的 x64 和 arm64 后合并
      - name: Package x64 (unsigned) for universal build
        if: matrix.arch == 'universal'
        env:
          NODE_OPTIONS: --max-old-space-size=8192
          SKIP_CODESIGN: true
        run: pnpm run package -- --arch=x64

      - name: Package arm64 (unsigned) for universal build
        if: matrix.arch == 'universal'
        env:
          NODE_OPTIONS: --max-old-space-size=8192
          SKIP_CODESIGN: true
        run: pnpm run package -- --arch=arm64

      - name: Create universal binary
        if: matrix.arch == 'universal'
        env:
          NODE_OPTIONS: --max-old-space-size=8192
        run: pnpm run package:universal

      - name: Create distributable and publish (universal)
        if: matrix.arch == 'universal'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_OPTIONS: --max-old-space-size=8192
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        run: |
          # 创建分发文件 (DMG 和 ZIP)
          pnpm run make -- --arch=universal
          # 发布到 GitHub Release
          VERSION=${GITHUB_REF#refs/tags/}
          find out/make -name "*.dmg" -exec gh release upload "$VERSION" {} --clobber \;
          find out/make/zip -name "*.zip" -exec gh release upload "$VERSION" {} --clobber \;

      - name: Upload artifacts (Windows)
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: windows-artifacts
          path: |
            out/make/squirrel.windows/**/*
            out/make/zip/win32/**/*
            out/make/wix/win32/**/*

      - name: Upload artifacts (macOS)
        if: startsWith(matrix.os, 'macos-') && matrix.arch != 'universal'
        uses: actions/upload-artifact@v4
        with:
          name: macos-${{ matrix.arch }}-artifacts
          path: |
            out/make/*.dmg
            out/make/zip/**/*

      - name: Upload artifacts (macOS universal)
        if: matrix.arch == 'universal'
        uses: actions/upload-artifact@v4
        with:
          name: macos-universal-artifacts
          path: |
            out/make/*.dmg
            out/make/zip/**/*

      - name: Upload artifacts (Linux)
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: linux-artifacts
          path: |
            out/make/deb/**/*
            out/make/rpm/**/*
